---
sidebar: sidebar 
permalink: docs/concept_hci_volumes.html 
summary: Un volume 
keywords: netapp, hci, storage volume, solidfire volume, element volume, persistent volume 
---
= Volumi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Il provisioning dello storage viene eseguito nel sistema NetApp Element come volumi. I volumi sono dispositivi a blocchi a cui si accede in rete utilizzando client iSCSI o Fibre Channel.

Il plug-in NetApp Element per vCenter Server consente di creare, visualizzare, modificare, eliminare, clonare, backup o ripristino dei volumi per gli account utente. È inoltre possibile gestire ciascun volume di un cluster e aggiungere o rimuovere volumi in gruppi di accesso ai volumi.



== Volumi persistenti

I volumi persistenti consentono ai dati di configurazione dei nodi di gestione di essere memorizzati in un cluster di storage specifico, piuttosto che localmente con una macchina virtuale, in modo che i dati possano essere conservati in caso di perdita o rimozione dei nodi di gestione. I volumi persistenti sono una configurazione del nodo di gestione opzionale ma consigliata.

Se si implementa un nodo di gestione per NetApp HCI utilizzando il motore di implementazione NetApp, i volumi persistenti vengono attivati e configurati automaticamente.

Un'opzione per abilitare i volumi persistenti è inclusa negli script di installazione e aggiornamento quando si implementa un nuovo nodo di gestione. I volumi persistenti sono volumi su un cluster di storage basato su software Element che contengono informazioni di configurazione del nodo di gestione per la VM del nodo di gestione host che persistono oltre la vita della macchina virtuale. In caso di perdita del nodo di gestione, una macchina virtuale del nodo di gestione sostitutivo può riconnettersi e ripristinare i dati di configurazione per la macchina virtuale persa.

La funzionalità dei volumi persistenti, se attivata durante l'installazione o l'aggiornamento, crea automaticamente più volumi con NetApp-HCI pre-messo in attesa del nome sul cluster assegnato. Questi volumi, come qualsiasi volume basato su software Element, possono essere visualizzati utilizzando l'interfaccia utente Web del software Element, il plug-in NetApp Element per vCenter Server o l'API, a seconda delle preferenze e dell'installazione. I volumi persistenti devono essere attivi e in esecuzione con una connessione iSCSI al nodo di gestione per mantenere i dati di configurazione correnti che possono essere utilizzati per il ripristino.


NOTE: I volumi persistenti associati ai servizi di gestione vengono creati e assegnati a un nuovo account durante l'installazione o l'aggiornamento. Se si utilizzano volumi persistenti, non modificare o eliminare i volumi o l'account associato



== Trova ulteriori informazioni

* link:task_hcc_manage_vol_management.html["Gestire i volumi"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
* http://docs.netapp.com/sfe-122/index.jsp["Centro di documentazione software SolidFire ed Element"^]

