---
sidebar: sidebar 
permalink: docs/task_hci_credentials_vcenter_esxi.html 
summary: 'In un"installazione NetApp HCI, è possibile modificare le credenziali per gli host vCenter e ESXi per un nodo di calcolo gestito da NetApp Hybrid Cloud Control.' 
keywords: netapp, hci, password, credential, vcenter, esxi, hybrid cloud control 
---
= Aggiornare le credenziali vCenter ed ESXi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Per mantenere la piena funzionalità di NetApp Hybrid Cloud Control per la tua installazione NetApp HCI, quando modifichi le tue credenziali negli host vCenter ed ESXi, devi anche aggiornare tali credenziali nel servizio asset sul nodo di gestione.

.A proposito di questa attività
NetApp Hybrid Cloud Control comunica con vCenter e i singoli nodi di calcolo che eseguono VMware vSphere ESXi per recuperare le informazioni per la dashboard e facilitare gli aggiornamenti a rotazione di firmware, software e driver. NetApp Hybrid Cloud Control e i relativi servizi sul nodo di gestione utilizzano credenziali (nome utente/password) per l'autenticazione con VMware vCenter ed ESXi.

Se la comunicazione tra questi componenti non riesce, NetApp Hybrid Cloud Control e vCenter visualizzano messaggi di errore quando si verificano problemi di autenticazione. Se non riesce a comunicare con l'istanza di VMware vCenter associata nell'installazione di NetApp HCI, il controllo del cloud ibrido NetApp visualizza un banner di errore rosso. VMware vCenter visualizza i messaggi di blocco dell'account ESXi per i singoli host ESXi in seguito al NetApp Hybrid Cloud Control che utilizza credenziali obsolete.

Il nodo di gestione in NetApp HCI fa riferimento a questi componenti utilizzando i seguenti nomi:

* Le "risorse dei controller" sono istanze di vCenter associate all'installazione di NetApp HCI.
* Le "risorse dei nodi di calcolo" sono gli host ESXi presenti nell'installazione di NetApp HCI.


Durante l'installazione iniziale di NetApp HCI utilizzando il motore di implementazione NetApp, il nodo di gestione ha memorizzato le credenziali dell'utente amministrativo specificato per vCenter e la password dell'account "root" sui server ESXi.



== Aggiornare la password di vCenter utilizzando l'API REST del nodo di gestione

Seguire la procedura per aggiornare le risorse del controller. Vedere link:task_mnode_edit_vcenter_assets.html["Visualizzare o modificare le risorse dei controller esistenti"].



== Aggiornare la password ESXi utilizzando l'API REST del nodo di gestione

.Fasi
. Per una panoramica dell'interfaccia utente REST API del nodo di gestione, vedere link:task_mnode_work_overview_API.html["Panoramica dell'interfaccia utente REST API del nodo di gestione"].
. Accedere all'interfaccia utente API REST per i servizi di gestione sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
Sostituire <management node IP> con l'indirizzo IPv4 del nodo di gestione sulla rete di gestione utilizzata per NetApp HCI.

. Fare clic su *autorizzare* o su un'icona a forma di lucchetto e completare le seguenti operazioni:
+
.. Inserire il nome utente e la password amministrativi del cluster NetApp SolidFire.
.. Immettere l'ID client come `mnode-client`.
.. Fare clic su *autorizzare* per avviare una sessione.
.. Chiudere la finestra.


. Dall'interfaccia utente API REST, fare clic su *GET ​/Assets/compute_nodes*.
+
In questo modo vengono recuperati i record delle risorse dei nodi di calcolo memorizzate nel nodo di gestione.

+
Di seguito viene riportato il collegamento diretto a questa API nell'interfaccia utente:

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.get_compute_nodes
----
. Fare clic su *Provalo*.
. Fare clic su *Execute* (Esegui).
. Dal corpo di risposta, identificare i record delle risorse del nodo di calcolo che richiedono credenziali aggiornate. È possibile utilizzare le proprietà "ip" e "nome_host" per trovare i record host ESXi corretti.
+
[listing]
----
"config": { },
"credentialid": <credential_id>,
"hardware_tag": <tag>,
"host_name": <host_name>,
"id": <id>,
"ip": <ip>,
"parent": <parent>,
"type": ESXi Host
----
+

NOTE: Il passaggio successivo utilizza i campi "padre" e "id" nel record di risorsa di calcolo per fare riferimento al record da aggiornare.

. Configurare la risorsa specifica del nodo di calcolo:
+
.. Fare clic su *PUT /assets/{asset_id}/compute-nodes/{compute_id}*.
+
Di seguito viene riportato il collegamento diretto all'API nell'interfaccia utente:

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.put_assets_compute_id
----
.. Fare clic su *Provalo*.
.. Inserire l'"asset_id" con le informazioni "padre".
.. Inserire l'"ID_calcolo" con le informazioni "id".
.. Modificare il corpo della richiesta nell'interfaccia utente per aggiornare solo i parametri di password e nome utente nel record della risorsa di calcolo:
+
[listing]
----
{
"password": "<password>",
"username": "<username>"
}
----
.. Fare clic su *Execute* (Esegui).
.. Verificare che la risposta sia HTTP 200, che indica che le nuove credenziali sono state memorizzate nel record delle risorse di calcolo a cui si fa riferimento


. Ripetere i due passaggi precedenti per le risorse aggiuntive dei nodi di calcolo che devono essere aggiornate con una nuova password.
. Selezionare https://<mNode_ip>/inventory/1/[].
+
.. Fare clic su *autorizzare* o su un'icona a forma di lucchetto e completare le seguenti operazioni:
+
... Inserire il nome utente e la password amministrativi del cluster NetApp SolidFire.
... Immettere l'ID client come `mnode-client`.
... Fare clic su *autorizzare* per avviare una sessione.
... Chiudere la finestra.


.. Dall'interfaccia utente API REST, fare clic su *GET /Installations*.
.. Fare clic su *Provalo*.
.. Selezionare *True* dall'elenco a discesa Refresh description (Descrizione aggiornamento).
.. Fare clic su *Execute* (Esegui).
.. Verificare che la risposta sia HTTP 200.


. Attendere circa 15 minuti per far scomparire il messaggio di blocco dell'account in vCenter.


[discrete]
== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Pagina delle risorse NetApp HCI"^]

