---
sidebar: sidebar 
permalink: docs/task_mnode_add_assets.html 
summary: 'È possibile aggiungere risorse di calcolo e controller alla configurazione del nodo di gestione utilizzando l"interfaccia utente REST API.' 
keywords: netapp, mnode, management node, rest api, hci 
---
= Aggiungere risorse di calcolo e controller al nodo di gestione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere risorse di calcolo e controller alla configurazione del nodo di gestione utilizzando l'interfaccia utente REST API.

Potrebbe essere necessario aggiungere una risorsa se l'installazione è stata scalata di recente e le nuove risorse non sono state aggiunte automaticamente alla configurazione. Utilizza queste API per aggiungere risorse aggiunte di recente all'installazione.

.Di cosa hai bisogno
* La versione del cluster in uso esegue il software NetApp Element 11.3 o versione successiva.
* È stato implementato un nodo di gestione con versione 11.3 o successiva.
* Lo hai fatto link:task_mnode_create_netapp_hcc_role_vcenter.html["Ha creato un nuovo ruolo NetApp HCC in vCenter"] Per limitare la vista dei servizi del nodo di gestione alle risorse solo NetApp.
* Si dispone dell'indirizzo IP e delle credenziali per la gestione di vCenter.
* Si dispone dell'indirizzo IP di gestione del nodo di calcolo (ESXi) e delle credenziali root.
* Si dispone dell'indirizzo IP di gestione dell'hardware (BMC) e delle credenziali di amministratore.


.A proposito di questa attività
(Solo NetApp HCI) se non vengono visualizzati nodi di calcolo nel controllo del cloud ibrido (HCC) dopo aver scalato il sistema NetApp HCI, è possibile aggiungere un nodo di calcolo utilizzando `POST /assets/{asset_id}/compute-nodes` descritto in questa procedura.


NOTE: Quando si aggiungono manualmente i nodi di calcolo, assicurarsi di aggiungere anche le risorse BMC, altrimenti viene restituito un errore.

.Fasi
. Ottenere l'ID risorsa di base per l'installazione:
+
.. Aprire l'interfaccia utente REST API del servizio di inventario sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Selezionare *autorizzare* e completare le seguenti operazioni:
+
... Inserire il nome utente e la password del cluster.
... Immettere l'ID client come `mnode-client`.
... Selezionare *autorizzare* per avviare una sessione.
... Chiudere la finestra.


.. Dall'interfaccia utente API REST, selezionare *GET ​/Installations*.
.. Selezionare *Provalo*.
.. Selezionare *Esegui*.
.. Dal corpo della risposta del codice 200, copiare il `id` per l'installazione.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: L'installazione dispone di una configurazione delle risorse di base creata durante l'installazione o l'aggiornamento.

.. Dall'interfaccia utente API REST, selezionare *GET /Installations/{id}*.
.. Selezionare *Provalo*.
.. Incollare l'ID della risorsa di installazione nel campo *id*.
.. Selezionare *Esegui*.
.. Dalla risposta, copiare e salvare l'ID del controller del cluster (`"controllerId"`) da utilizzare in un passaggio successivo.


. (Solo per nodi di calcolo) xref:task_mnode_locate_hardware_tag.adoc[Individuare il tag hardware per il nodo di calcolo] In vSphere.
. Per aggiungere una risorsa controller (vCenter), un nodo di calcolo (ESXi) o un hardware (BMC) a una risorsa di base esistente, selezionare una delle seguenti opzioni.
+
[cols="40,60"]
|===
| Opzione | Descrizione 


| POST /Assets/{asset_id}/controller  a| 
.. Aprire l'interfaccia utente dell'API REST del servizio mNode sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
... Selezionare *autorizzare* e completare le seguenti operazioni:
+
.... Inserire il nome utente e la password del cluster.
.... Immettere l'ID client come `mnode-client`.
.... Selezionare *autorizzare* per avviare una sessione.
.... Chiudere la finestra.




.. Selezionare *POST /assets/{asset_id}/controller*.
.. Selezionare *Provalo*.
.. Inserire l'ID risorsa di base principale nel campo *asset_id*.
.. Aggiungere i valori richiesti al payload.
.. Selezionare *Esegui*.




| POST /assets/{asset_id}/nodi di calcolo  a| 
.. Aprire l'interfaccia utente dell'API REST del servizio mNode sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
... Selezionare *autorizzare* e completare le seguenti operazioni:
+
.... Inserire il nome utente e la password del cluster.
.... Immettere l'ID client come `mnode-client`.
.... Selezionare *autorizzare* per avviare una sessione.
.... Chiudere la finestra.




.. Selezionare *POST /assets/{asset_id}/compute-nodes*.
.. Selezionare *Provalo*.
.. Inserire l'ID risorsa base principale copiato in un passaggio precedente nel campo *asset_id*.
.. Nel payload, procedere come segue:
+
... Inserire l'IP di gestione per il nodo in `ip` campo.
... Per `hardwareTag`, inserire il valore del tag hardware salvato in una fase precedente.
... Inserire altri valori, come richiesto.


.. Selezionare *Esegui*.




| POST /assets/{asset_id}/nodi-hardware  a| 
.. Aprire l'interfaccia utente dell'API REST del servizio mNode sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
... Selezionare *autorizzare* e completare le seguenti operazioni:
+
.... Inserire il nome utente e la password del cluster.
.... Immettere l'ID client come `mnode-client`.
.... Selezionare *autorizzare* per avviare una sessione.
.... Chiudere la finestra.




.. Selezionare *POST /assets/{asset_id}/hardware-nodes*.
.. Selezionare *Provalo*.
.. Inserire l'ID risorsa di base principale nel campo *asset_id*.
.. Aggiungere i valori richiesti al payload.
.. Selezionare *Esegui*.


|===


[discrete]
== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Pagina delle risorse NetApp HCI"^]

