---
sidebar: sidebar 
permalink: docs/task_mnode_enable_remote_support_connections.html 
summary: 'È possibile utilizzare il nodo di gestione per abilitare l"accesso al supporto NetApp per la risoluzione dei problemi.' 
keywords: netapp, mnode, management node, connect to support, support tunnel, rst 
---
= Avviare una sessione remota di NetApp Support
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se hai bisogno di supporto tecnico per il tuo sistema NetApp HCI, il supporto NetApp può connetterti in remoto con il tuo sistema. Per avviare una sessione e ottenere l'accesso remoto, il supporto NetApp può aprire una connessione Secure Shell (SSH) inversa al proprio ambiente.

Con il supporto NetApp è possibile aprire una porta TCP per una connessione a tunnel inverso SSH. Questa connessione consente al supporto NetApp di accedere al nodo di gestione.

.Prima di iniziare
* Per i servizi di gestione 2.18 e versioni successive, la funzionalità di accesso remoto è disattivata per impostazione predefinita nel nodo di gestione. Per attivare la funzionalità di accesso remoto, vedere link:task_mnode_ssh_management.html["Gestire la funzionalità SSH sul nodo di gestione"].
* Se il nodo di gestione si trova dietro un server proxy, nel file sshd.config sono necessarie le seguenti porte TCP:
+
[cols="15,25,60"]
|===
| Porta TCP | Descrizione | Direzione di connessione 


| 443 | Chiamate API/HTTPS per l'inoltro inverso delle porte all'interfaccia utente Web tramite tunnel di supporto aperto | Nodo di gestione ai nodi di storage 


| 22 | Accesso SSH | Nodo di gestione per nodi di storage o da nodi di storage a nodi di gestione 
|===


.Fasi
* Accedere al nodo di gestione e aprire una sessione terminale.
* Quando richiesto, immettere quanto segue:
+
`rst -r  sfsupport.solidfire.com -u element -p <port_number>`

* Per chiudere il tunnel di supporto remoto, immettere quanto segue:
+
`rst --killall`

* (Facoltativo) Disattiva link:task_mnode_ssh_management.html["funzionalità di accesso remoto"] di nuovo.
+

NOTE: SSH rimane attivato se non viene disattivato. La configurazione abilitata SSH persiste sul nodo di gestione tramite aggiornamenti e aggiornamenti fino a quando non viene disattivata manualmente.





== Trova ulteriori informazioni

https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
