---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_compute_firmware_ansible.html 
summary: 'Per i nodi di calcolo della serie H, NetApp offre un ruolo Ansible che consente di automatizzare l"aggiornamento del firmware per componenti hardware come BMC, BIOS e NIC.' 
keywords: netapp, hci, on premise, cluster, element, compute node, ansible upgrade, upgrade role 
---
= Automatizza gli aggiornamenti del firmware dei nodi di calcolo con Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare il firmware di sistema sui nodi di calcolo NetApp HCI, incluso il firmware per componenti come BMC, BIOS e NIC, utilizzando i flussi di lavoro in NetApp Hybrid Cloud Control. Per le installazioni con cluster di calcolo di grandi dimensioni, è possibile automatizzare i flussi di lavoro utilizzando Ansible per eseguire un aggiornamento continuo dell'intero cluster.


NOTE: Mentre il ruolo Ansible per automatizzare gli aggiornamenti del firmware dei nodi di calcolo è reso disponibile da NetApp, l'automazione è un componente ausiliario che richiede una configurazione aggiuntiva e l'esecuzione di componenti software. La modifica dell'automazione Ansible è supportata solo con il massimo sforzo.


NOTE: Il ruolo Ansible per gli upgrade funziona solo sui nodi di calcolo NetApp HCI serie H. Non è possibile utilizzare questo ruolo per aggiornare i nodi di calcolo di terze parti.

.Di cosa hai bisogno
* *Disponibilità e prerequisiti per gli aggiornamenti del firmware*: L'installazione di NetApp HCI deve essere pronta per l'aggiornamento del firmware, come indicato nelle istruzioni per link:task_hcc_upgrade_compute_node_firmware.html["esecuzione degli aggiornamenti del firmware"].
* *Possibilità di eseguire l'automazione sul nodo di controllo Ansible*: Un server fisico o virtuale per eseguire l'automazione dell'aggiornamento del firmware in Ansible.


.A proposito di questa attività
In un ambiente di produzione, è necessario aggiornare i nodi di calcolo in un cluster in un'installazione NetApp HCI in modo variabile; un nodo alla volta, uno alla volta. Le API di NetApp Hybrid Cloud Control orchestrano il processo di aggiornamento del firmware del nodo di calcolo complessivo per un singolo nodo di calcolo, tra cui l'esecuzione di controlli dello stato di salute, il posizionamento di ESXi sui nodi di calcolo e il riavvio del nodo di calcolo per applicare gli aggiornamenti del firmware. Il ruolo Ansible consente di orchestrare l'aggiornamento del firmware per un gruppo di nodi di calcolo o interi cluster.

.Inizia a utilizzare l'automazione dell'aggiornamento del firmware
Per iniziare, accedere a. https://github.com/NetApp-Automation/nar_compute_firmware_upgrade["Repository NetApp Ansible su GitHub"^] e scaricare `nar_compute_nodes_firmware_upgrades` ruolo e documentazione.
