---
sidebar: sidebar 
permalink: docs/task_nde_configure_credentials.html 
summary: 'Scopri come configurare VMware vSphere durante l"implementazione di NetApp HCI.' 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= Configurazione delle credenziali NetApp HCI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere, vcenter, credentials, user accounts, administrator


[role="lead"]
Durante l'implementazione, è possibile definire un set di credenziali da utilizzare nell'ambiente VMware vSphere appena implementato, nelle risorse di calcolo e storage NetApp HCI e nel nodo di gestione. Se si implementa NetApp HCI in un ambiente vSphere esistente, queste credenziali non vengono applicate al server vCenter esistente.

.A proposito di questa attività
Tenere presenti i seguenti punti relativi alle credenziali impostate nel motore di implementazione di NetApp HCI:

* *NetApp Hybrid Cloud Control (HCC) o Element UI*: Per accedere a NetApp HCC o all'interfaccia utente Element una volta completata l'implementazione, utilizzare il nome utente e la password specificati in questa fase di implementazione.
* *VMware vCenter*: Per accedere a vCenter (se installato come parte dell'implementazione), utilizzare il nome utente con il suffisso `@vsphere.local` o il integrato `Administrator@vsphere.local` e la password specificata in questa fase di implementazione.
* *VMware ESXi*: Per accedere a ESXi sui nodi di calcolo, utilizzare il nome utente `root` e la stessa password specificata in questa fase di implementazione.


Per l'interazione con le istanze di VMware vCenter, NetApp Hybrid Cloud Control utilizzerà uno dei seguenti metodi:

* Il sistema integrato `Administrator@vsphere.local` Account utente sull'istanza di vCenter installata come parte della distribuzione.
* Le credenziali vCenter utilizzate per connettere l'implementazione di NetApp HCI a un server vCenter esistente.


.Fasi
. Nella pagina *credenziali*, immettere un nome utente nel campo *Nome utente*.
. Inserire una password nel campo *Password*. La password deve essere conforme ai criteri visualizzati nella casella *la password deve contenere*.
. Confermare la password nel campo *Re-Enter Password*.
. Fare clic su *continua*.


[discrete]
== Trova ulteriori informazioni

* link:firmware_driver_versions.html["Versioni del firmware e dei driver ESXi supportate per NetApp HCI e versioni del firmware per i nodi di storage NetApp HCI"]
* Per aggiornare le credenziali vCenter ed ESXi in un secondo momento, vedere link:task_hci_credentials_vcenter_esxi.html["Aggiornare le credenziali vCenter o ESXi"].

